### ISSUE TITLE
GEDR3_4096 maintenance

### ISSUE THREAD

**Issue by Zarquan** [wfau/gaia-dmp#607]
We currently maintain four copies of the Gaia data in Parquet, each one is split into a different number of partitions.

* `GEDR3_2048`
* `GEDR3_4096`
* `GEDR3_8192`
* `GEDR3_11932`

The setup script loads the `GEDR3_2048` version into the Spark context, and as far as I can tell none of the other versions of the data are used in any of the active notebooks.

Do we need to maintain the other versions?

Reason for asking is we have detected a potential error in the `GEDR3_4096` copy. The error is in the file names, not in the actual data itself. We haven't looked into the details yet, I wanted to check to see if this was necessary before spending much time on it.

**Comment by NigelHambly** [comment]
IIRC the default partitioning is 2048, while the others were generated to test if smaller partition file sizes relieved memory stress on worker nodes. I'd suggest that you don't spend any time on investigating problems in test datasets, or generally maintaining them, if the tests themselves are not high priority and are not current. The problem is logged here and can be looked at in detail if/when testing of performance v. partition size becomes important again.

If on the other hand it's tidiness that's the real issue (or even disk space) then simply scrub them - they can be recreated as and when necessary with relatively little effort.

**Comment by Zarquan** [comment]
Our deployment automatically mounts all of the copies, and checks the directory contents to make sure the mount worked.

I noticed that the latest deployment is reporting an error in the directory contents for `GEDR3_4096`. Could be just a file name is wrong, or the checksum we comparing it with is wrong.

As far as I know the data is fine.

Marking this as a low priority and moving on to other things.

**Comment by NigelHambly** [comment]
Closing this as old-hat. There's a new issue (#952) raised in relation to partitioning which is far more relevant looking forward to scale-up after DR3. The main issue is the Spark-internal limitation in serialising in-memory partitions using Java byte[] arrays which have a 2.1 GB limit from the 4-byte signed integer indexing. For example the XP spectra at DR3 are a ~10% sampling (220M spectra in a catalogue of 1800M). Spread over 2048 partitions this results in 1.4 GB partition files, which is right at the limit of handling in workers given other overheads. So we'll need to substantially up the number of partitions at DR4. In any case, see the linked issue for more on this.

**Comment by NigelHambly** [comment]
Yeah scrub 'em. I'm not worried about performance: the constraint on choice of this number comes from the size of the largest data types.

**Comment by Zarquan** [comment]
OK, closing this and adding a task for me to do that, #1017
