### ISSUE TITLE
Process for registering users

### ISSUE THREAD

**Issue by Zarquan** [wfau/gaia-dmp#852]
We need to create a process for registering new users and managing their login accounts.
* Welcome email describing the platform.
* HowTo pages describing what home directories and user data directories are for.
* HowTo pages describing how we manage access to the platform.

How do we manage access to the platform.
* If we have < 10 users, do we let them all just go ahead and use it
* If we have > 10 users, do we need to limit access
* Can we wait until the system starts to slow down
* Do we need to put anything in place to make it easier to manage later

**Comment by NigelHambly** [comment]
Initial thoughts on welcome email:

- Point to the example notebooks as the description rather than duplicating that info on e.g. a Wiki
- Note the front page is the Zeppelin UI home/login which says nothing about Gaia DMP (this has already been noted by a potential user)
- Cautions: 
- - shared resource, please use responsibly; help is available via support email address (we should always set the reply-to address when responding to requests so that everything is visible to all... I've already broken that rule!)
- - "Support is provided on a best-efforts basis. Please note in particular that preserving your notebooks and data extractions is your own responsibility. In the event of loss of platform service or the Cloud infrastructure on which it is built we will endeavour to restore the system to it's last working state but cannot guarantee all user notebooks and data will be backed-up so please download notebooks regularly and copy derived data off the platform promptly."
- "Do you wish to receive service announcements concerning maintenance, unavailability etc. (you can opt out at any time simply by contacting gaiadmp-support) YES/NO" ... is there a straightforward way for us to maintain and share a distribution list of emails for this?

**Comment by Zarquan** [comment]
We have the beginnings of a process.
* We have a template for the [welcome email](https://github.com/wfau/gaia-dmp/blob/master/docs/emails/welcome-email.txt)
* The create-user scripts automatically allocate a 1G `/home` and a 10G `/user` CephFS share to each user.
* We have a support email address for users top contact us <gaiadmp-support@roe.ac.uk>.
* We have a [Slack channel](https://gaia-dmp.slack.com/) ready, although we haven't published it to users yet.

Suggest we close this issue as done and start new issues with the tag `user-crm` for new things.
