### ISSUE TITLE
Check who can stop/start interpreters

### ISSUE THREAD

**Issue by Zarquan** [wfau/gaia-dmp#931]
Check that normal users can stop/start their interpreters when they need to.

**Comment by NigelHambly** [comment]
Dennis and I cannot restart the python interpreter on the current live system via the cog at the top right-hand side of the Zeppelin UI. This has (mainly) worked in the past and can be quite useful when a user's python interpreter ties itself in knots because of multiple invocations of notebook cells etc.

**Comment by stvoutsin** [comment]
This should be fixed in the most recent version. I've checked and I can restart my interpreters from my account. @NigelHambly Could you check that you can restart as well? If its ok do we classify this as done?

**Comment by NigelHambly** [comment]
Works fine for me too many thanks. Closing this as done.

**Comment by Zarquan** [comment]
We need to create a scripted test to check this always works #1115.
