### ISSUE TITLE
ALLWISE crossmatched table not working.

### ISSUE THREAD

**Issue by NigelHambly** [wfau/gaia-dmp#962]
There is a bug in gaiadmpsetup in that the ALLWISE crossmatched table is attached against the incorrect schema (cut-and-pasted 2MASS by mistake). This means that the table resource cannot be used. 

Fix asap!

**Comment by Zarquan** [comment]
We need a set of simple test notebooks, one for each table, that verify that the table has the right columns and it has the right rowcount. Issue #910 covers part of it, but we should probably do this for all the tables.

**Comment by Zarquan** [comment]
* Created a new release of gaiadmpsetup
  https://github.com/wfau/gaiadmpsetup/releases/tag/v0.1.3

* Created a new deployment of Aglais with new version of gaiadmpsetup
  https://github.com/Zarquan/aglais/blob/20220810-zrq-allwise-test/notes/zrq/20220810-01-allwise-test.txt  

Running an example notebook fails with error message:
```
Fail to execute line 2: import gaiadmpsetup
Traceback (most recent call last):
  File "/tmp/1660140247287-0/zeppelin_python.py", line 153, in <module>
    exec(code, _zcUserQueryNameSpace)
  File "<stdin>", line 2, in <module>
  File "/usr/local/lib/python3.7/site-packages/gaiadmpsetup/__init__.py", line 1, in <module>
    from . import gaiadmpsetup
  File "/usr/local/lib/python3.7/site-packages/gaiadmpsetup/gaiadmpsetup.py", line 6, in <module>
    from . import gaiadr3_pyspark_schema_structures as dr3
  File "/usr/local/lib/python3.7/site-packages/gaiadmpsetup/gaiadr3_pyspark_schema_structures.py", line 1571, in <module>
    from gaiaedr3_pyspark_schema_structures import tmasspscxsc_best_neighbour_schema, twomass_psc_schema, allwise_best_neighbour_schema, allwise_sc_schema, panstarrs1_best_neighbour_schema, panstarrs_dr1_otmo_schema
ModuleNotFoundError: No module named 'gaiaedr3_pyspark_schema_structures'
```

Unfortunately the new deployment isn't accessible from outside because a side effect of the way that HTTPS was added to the live service has blocked all access to test deployments. Task #838 will restore access to test deployments but it hasn't been implemented yet.

**Comment by NigelHambly** [comment]
OK my bad - I've fallen foul of this python import stuff before - I don't understand the packaging structure of the library. @stvoutsin will need to review and correct.

**Comment by NigelHambly** [comment]
Tested successfully on latest test deploy: http://blue.gaia-dmp.uk:8080/#/notebook/2HA64ZWQX
